### ISSUE TITLE
Feature Request: Support backup of VM's with Delete Protection

### ISSUE THREAD

**Issue by steve--d** [wefixit-AT/oVirtBackup#10] opened 2016-02-18 23:59 UTC
It would be awesome if it was possible to backup VM's which have 'Delete Protection' enabled.

Feb 18 15:37:37: Start backup for: t-c7-comp
Feb 18 15:37:42: Snapshot creation started ...
Feb 18 15:38:43: Snapshot created
Feb 18 15:38:44: Clone into VM started ...
Feb 18 15:40:47: Cloning finished
Feb 18 15:40:48: Snapshot deletion started ...
Feb 18 15:41:48: Snapshots deleted
Feb 18 15:41:50: Export started ...
Feb 18 15:42:51: Exporting finished
Feb 18 15:42:56: Delete cloned VM started ...
Feb 18 15:42:57: !!! Can't delete cloned VM (t-c7-comp_BKUP_20160218_153737)
Feb 18 15:42:57: !!! Got a RequestError: 
status: 409
reason: Conflict
detail: Cannot remove VM. Delete protection is enabled. In order to delete, disable Delete protection first.
Feb 18 15:42:57: All backups done
Feb 18 15:42:57: Backup failured for:
Feb 18 15:42:57:   t-c7-comp
Feb 18 15:42:57: Some errors occured during the backup, please check the log file

I would hazard a guess that if delete protection was removed after VM was cloned from snapshot this would work correctly. I can't find much mention about how to do this, although it appears possible, search for "added deletion protection to the template/vm via .delete_protected" here: http://www.ovirt.org/develop/sdk/python-sdk-changelog/

**Comment by wefixit-AT** [comment] 2016-03-01 14:08
Thanks for reporting this. Can you please checkout the latest version and give a short feedback if I can close this request.

**Comment by scotthesterberg** [comment] 2016-03-01 16:03
This is awesome, I was going to work on this today as I ran into the same issue. Thanks, I tested it and it works.

**Comment by steve--d** [comment] 2016-03-02 18:18
I'm getting an error:

# ./backup.py -c config.cfg 
Mar 02 10:04:59: Start backup for: template-centos7-compute
Mar 02 10:05:05: !!! Got unexpected exception: 'NoneType' object has no attribute 'available'

This happens if delete protection is either enabled or disabled.

I'm running Ovirt version 3.5.3.1-1.el7.centos.

Tailing engine logs while running script:
# tail -f /var/log/ovirt-engine/engine.log &
# ./backup.py -c config.cfg 
2016-03-02 10:12:16,669 INFO  [org.ovirt.engine.core.bll.aaa.LoginUserCommand] (ajp--127.0.0.1-8702-5) Running command: LoginUserCommand internal: false.
2016-03-02 10:12:16,671 INFO  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (ajp--127.0.0.1-8702-5) Correlation ID: null, Call Stack: null, Custom Event ID: -1, Message: User admin@internal logged in.
Mar 02 10:12:17: Start backup for: template-centos7-compute
Mar 02 10:12:23: !!! Got unexpected exception: 'NoneType' object has no attribute 'available'

**Comment by wefixit-AT** [comment] 2016-03-02 18:56
Hi, I can't reproduce this on my machine maybe because I use a newer version of oVirt (3.6.1.3-1.el7.centos.noarch).

Do you plan to upgrade? To fix this problem I have to install the same oVirt version, to test if other problems occur and then I have to code some workarounds for that old oVirt version. Because this will take a long time I plan this for next week if this is really needed. Besides redhat fixed many issues in 3.6.

**Comment by steve--d** [comment] 2016-03-02 19:18
I have some hooks I depend on that I don't see getting tested on 3.6 in the near future. Its not critical to get this feature support, just a nice to have so if you can get to 3.5 support at some point that would be awesome, but not at all expected.

And thanks for your work on this project, very useful!

**Closed** 2016-07-03 07:07 UTC
